version: '3'

services:
  server:
    build: .
    depends_on:
      - 'database'
    ports: 
      - '80:80'

  database:
    image: postgres:latest
    environment: 
      POSTGRES_USER: jonlau
      POSTGRES_DB: youtube